spring:
  application:
    name: cloud-file-storage
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_USER}
  secret-key: ${MINIO_PASSWORD}

server:
  servlet:
    session:
      timeout: 24h
  error:
    include-message: always